name: CD

on:
  push:
    branches:
      - main

jobs:
  build-annie:
    name: Build annie
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login into Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login into GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: ./annie
          push: true
          tags:
            - ${{ secrets.DOCKERHUB_USERNAME }}/annie:latest
            - ghcr.io/${{ github.actor }}/annie:latest
          labels: |
            org.opencontainers.image.title=Annie
            org.opencontainers.image.url=https://github.com/${{ github.repository }}/tree/main/annie
            org.opencontainers.image.documentation=https://github.com/${{ github.repository }}/tree/main/annie/README.md
            org.opencontainers.image.source=https://github.com/${{ github.repository }}/tree/main/annie