name: CD

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  build-annie:
    name: Build annie
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: ${{ github.actor }}/annie
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./annie
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest